name = "test-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "test-email"
database_id = "<D1_DATABASE_ID>"

[[kv_namespaces]]
binding = "kv"
id = "<KV_NAMESPACE_ID>"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "test-email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["*/30 * * * *", "0 16 * * *"]

[vars]
ai_model = ""
analysis_cache = false
orm_log = false
domain = ["example.com"]
admin = "admin@example.com"
jwt_secret = "<JWT_SECRET>"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
